### ISSUE TITLE
Directing users to this project

### ISSUE THREAD

**Issue by XenHat** [passionate-coder/Classic-Start#17]
I wanted to post in the Classic Shell forum to help users post the issues they are experiencing in here so that we can actually fix them, however...
![image](https://user-images.githubusercontent.com/980408/41651966-e52408ae-744f-11e8-83c6-dae2f3864cba.png)

Can someone post in http://www.classicshell.net/forum/viewtopic.php?f=17&t=8147 ?

**Comment by coddec** [comment]
Sure thing, on it now

**Comment by coddec** [comment]
Done
http://www.classicshell.net/forum/viewtopic.php?f=17&t=8147&p=35874#p35874

**Comment by XenHat** [comment]
If anyone misses that post, they need better glasses than me 🤣

**Comment by coddec** [comment]
> If anyone misses that post, they need better glasses than me 🤣

Agreed! Hahahahaha 😆 😆
