### ISSUE TITLE
New Feature: Adjust Window Size

### ISSUE THREAD

**Issue by Kizaemon** [passionate-coder/Classic-Start#2]
Thank you Passionate Coder and all team members for taking on this invaluable program.

May I suggest a new feature for Classic Start/Shell?

It happens all too often that a non-maximized window appears to be maximized.
One pixel wide space remains between the edge of desktop and the windows border.

For me this happens when the screen changes resolution on detaching of external monitor from my notebook. At the external 4k monitor the window was maximized, but when detached, the resolution goes down to the notebook's native resolution and the window is losing its maximized state, leaving one pixel wide gap to the desktop edge.

Not sure why and how this behavior was coded. But it leads to a big annoyance.

Normally, when the window is maximized it is enough to click with the mouse in the right upper corner, without paying attention where the click lands. Using the upper right corner is a great time saver for closing windows. But if there is a gap, the window below the current window is being closed unintentionally.

It would be great to have a program to monitor for such gaps and prevent these.
This can be done by adjusting the window size or position to either close the gap (by widening the window) or widen the gap to 10-20 pixels (by shrinking window size), so the gap is obvious.

I believe Classic Shell would be the right tool to host such functionality.

Regards

**Comment by Nodens-** [comment]
Not feasible. This is related to the window manager and has to do with resizing the desktop. What you're asking can not be done for several technical reasons.

**Comment by coddec** [comment]
If it's doable, it should be a new utility instead making Classic Start bloat.

**Comment by coddec** [comment]
@Kizaemon 
Tip: You can just pay 1s more attention at the corner, see the red X belongs to which window, before clicking on it.

![x1](https://user-images.githubusercontent.com/12678338/39975068-c8a46496-576f-11e8-942c-15632a2c27f0.png)


![x2](https://user-images.githubusercontent.com/12678338/39975070-c97d9554-576f-11e8-977b-303e37c0800c.png)
