### ISSUE TITLE
[Request] Convert localization *.dll files into simple text.

### ISSUE THREAD

**Issue by isshininu** [passionate-coder/Classic-Start#27]

**Comment by XenHat** [comment]
![image](https://user-images.githubusercontent.com/980408/42128352-6df8b1be-7c77-11e8-9ddb-4e5a16c8c4ad.png)
🤔

**Comment by isshininu** [comment]
Oops.
I mean localization DLL-files, of course. (like ru-RU.dll and etc)
They already contained localization in simple text and some other resources.

**Comment by XenHat** [comment]
DLL translation resources are a last resort and I would not encourage performing translations this way. The source text files are already present and I do not see a reason to not use them. (I'm not familiar with DLL *hacking*)

**Comment by XenHat** [comment]
Transplant of https://github.com/passionate-coder/Classic-Start/pull/8#issuecomment-399834865:

Reading Localization.rtf, I found a few things:

- We do not have a CSV -> DLL converter (Ivo *used to* accept <lang>.csv and created a DLL from that).
- DLL editing is only *one* of the supported translation methods
- The DLL are regenerated as needed, and only used to override the `L10N` files
- The **main** method to translate Classic Start is to edit the three (3) `L10N.ini` files:
   1.  `ClassicStartSrc/ClassicExplorer/ExplorerL10N.ini`
   2. `ClassicStartSrc/ClassicStartMenu/StartMenuL10N.ini`
   3. `ClassicStartSrc/ClassicStartMenu/StartMenuHelper/StartMenuHelperL10N.ini`
   - **Installer** translation:
      - `ClassicStartSrc/Localization/WixUI/<lang>.wxl` (plain text)
   - **Policy** translation:
      - `ClassicStartSrc/Localization/<language>/*ADMX.txt` files

`ClassicStartLoc` appears to be an example and is not referenced anywhere in the code or the build scripts. It can probably be removed.

@Rukoto in your care you need to modify the section titled `[ja-JP] - Japanese (Japan)`:
![image](https://user-images.githubusercontent.com/980408/41831686-79692174-7816-11e8-8731-0e648104e505.png)
 etc

**The instructions above should be used to translate the program without DLL hacking.**

**Comment by coddec** [comment]
>I created a Wiki page to centralize information about localization: https://github.com/passionate-coder/Classic-Start/wiki/Localization-instructions

Really helpful for ppl to understand how to help to translate!
👍
