### ISSUE TITLE
Use github's releases to distribute binaries

### ISSUE THREAD

**Issue by Aokromes** [passionate-coder/Classic-Start#3]
IMHO instead having to use 3rd party servers it can be a good idea to use https://github.com/passionate-coder/Classic-Start/releases to distribute binaries.

**Comment by coddec** [comment]
> IMHO instead having to use 3rd party servers it can be a good idea to use https://github.com/passionate-coder/Classic-Start/releases to distribute binaries.

@ge0rdi
I think that is our plan?
Appveyor is for build testing right? No?

**Comment by ge0rdi** [comment]
Sure.

Official releases will be hosted on GitHub.
Though for now there was nothing that could qualify that.

Appveyor builds could be treat as night builds. So it doesn't matter they are hosted on different server.
