### ISSUE TITLE
Classic Star Menu does not start with user login in Windows 10 April Update

### ISSUE THREAD

**Issue by jedikalimero** [passionate-coder/Classic-Start#5]
Since my PC updated Windows 10 to the April 2018 Update, Classic Start Menu does not appear anymore when I click on the Start button. Instead, I get the regular Windows 10 Start menu.

If I start it manually, then I have the Classic Star Menu until I log out or turn off the computer.
I have tried in the settings to uncheck "Start automatically for this user" under "General Behavior", restart the computer, check it again and restart again (Sometimes this technique works in other programs) but no way.
The only way I have found to bypass this issue is to add a link to Classic Start Menu in the Startup folder, but the option in the settings doesn't seem to work anymore.

**Comment by ge0rdi** [comment]
Try to run this from administrator console:
`"C:\Program Files\Classic Shell\ClassicStartMenu.exe" -upgrade`

**Comment by jedikalimero** [comment]
I already have version 4.3.1. I don't think there is any update after this one.

**Comment by ge0rdi** [comment]
That command should re-register Classic Shell in system.

**Comment by coddec** [comment]
Yes, or simply reinstall it again, fool prove way 😄

**Comment by jedikalimero** [comment]
Thanks. It worked!
