### ISSUE TITLE
How to add custom quick menu entry: e.g. Resource Monitor?

### ISSUE THREAD

**Issue by RedSkyRoad** [passionate-coder/Classic-Start#50]
Hi,

When I want to add windows' "Resource Monitor" to the right side of the menu with the command **%windir%\system32\perfmon.exe /res**
it does nothing.

Any ideas?

**Comment by coddec** [comment]
@RedSkyRoad 
Custom Menu Item -> Insert new item -> Custom -> Click on the icon on the left hand side -> Command: %windir%\system32\perfmon.exe /res -> Label: Resource Monitor -> OK -> OK

**Comment by RedSkyRoad** [comment]
I tried it but it does nothing when I click the new link

**Comment by coddec** [comment]
Weird, it works on my side...

**Comment by RedSkyRoad** [comment]
Got it working.  I entered the string into "link" instead of the "command" field.

What is the difference between the two fields?

**Comment by coddec** [comment]
>What is the difference between the two fields?

Probably for url?

**Comment by RedSkyRoad** [comment]
I suggest you change the mouse-over information of the "link" field so it says something else.  It clearly states "Type a full path of a file or folder, e.g notepad.exe

**Comment by coddec** [comment]
Errr, @XenHat @ge0rdi 
Thoughts? 😕

**Comment by XenHat** [comment]
![image](https://user-images.githubusercontent.com/980408/43351218-e92d9456-91dc-11e8-8933-3f43bd1b29ec.png)

**Comment by XenHat** [comment]
![image](https://user-images.githubusercontent.com/980408/43352823-b8c8fa24-91f7-11e8-989f-a9346a16be10.png)
Interesting...
the "Link" entry appears to be for submenu entries.
